apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: kubis-gateway
spec:
  host: kubis-gateway
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: 0-1
    labels:
      version: 0-1
  - name: 0-1-d
    labels:
      version: 0-1-d
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kubis-gateway
spec:
  hosts:
    - kubis-gateway
  http:
  - route:
    - destination:
        host: kubis-gateway
        subset: 0-1
      weight: 100
    mirror:
      host: kubis-gateway 
      subset: 0-1-d
    corsPolicy:
      allowOrigin:
        - "*"
      allowMethods:
        - POST
        - GET
        - DELETE
        - PUT
        - OPTIONS
      allowHeaders:
        - "X-NEMO-AUTH"
        - "Origin"
        - "Accept"
        - "Content-Type"
        - "Authorization"
      exposeHeaders:
        - x-custom-header
      maxAge: 300s
      allowCredentials: true