apiVersion: v1
kind: ImageStream
metadata:
    name: kubis-rest
spec:
    tags:
    - from:
          kind: DockerImage
          name: docker-registry.default.svc:5000/kubis/kubis-rest
      name: latest
      importPolicy:
          scheduled: true
