kind: Service
apiVersion: v1
metadata:
  name: kubis-gw
  lables:
    app: kubis-gw
spec:
  selector:
    app: kubis-gw
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: kubis-rest
  lables:
    app: kubis-rest
spec:
  selector:
    app: kubis-rest
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
apiVersion: "v1"
kind: "DeploymentConfig"
metadata:
  name: kubis-gw
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: kubis-gw
        version: v0-1
        appGroup: kubis
    spec:
      serviceAccountName: kubis-gw
      containers:
      - name: kubis-gw
        image: docker-registry.default.svc:5000/kubis/kubis-gw:0.4
        env:
        - name: "JAVA_APP_JAR"
          value: "kubisgw-1.0.0-SNAPSHOT-fat.jar"
        ports:
        - containerPort: 8080
  replicas: 1
  triggers:
  - type: ConfigChange
  strategy:
    type: Rolling
---
apiVersion: "v1"
kind: "DeploymentConfig"
metadata:
  name: kubis-rest-0-3
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: kubis-rest
        version: v0-3
        appGroup: kubis
    spec:
      containers:
      - name: kubis-rest
        image: docker-registry.default.svc:5000/kubis/kubis-rest:0.3.6
        ports:
        - containerPort: 8080
  replicas: 1
  triggers:
  - type: ConfigChange
  strategy:
    type: Rolling
---
apiVersion: "v1"
kind: "DeploymentConfig"
metadata:
  name: tkit
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: tkit
        version: v0-1
        appGroup: kubis
    spec:
      serviceAccountName: tkit
      containers:
      - name: "tkit"
        image: "docker.io/dimssss/tkit:0.1"
        command: ["/bin/bash", "-c", "sleep 9999999"]
  replicas: 1
  triggers:
  - type: ConfigChange
  strategy:
    type: Rolling
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: kubis-gw
spec:
  host: kubis-gw
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: 0-1
    labels:
      version: v0-1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kubis-gw
spec:
  hosts:
    - kubis-gw
  http:
  - route:
    - destination:
        host: kubis-gw
        subset: 0-1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: kubis-rest
spec:
  host: kubis-rest
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: v0-3
    labels:
      version: v0-3
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kubis-rest
spec:
  hosts:
    - kubis-rest
  http:
  - route:
    - destination:
        host: kubis-rest
        subset: v0-3
