apiVersion: "v1"
kind: "DeploymentConfig"
metadata:
  name: kubis-rest-0-1
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: kubis-rest
        version: v0-1
    spec:
      containers:
      - name: kubis-rest
        image: "docker-registry.default.svc:5000/kubis/kubis-rest:0.1"
        ports:
        - containerPort: 8080
  replicas: 1
  triggers:
  - type: ConfigChange
  strategy:
    type: Rolling
  paused: false
  revisionHistoryLimit: 2
  minReadySeconds: 0
